## INSTALACION de Memcached y portal

data:
  image: postgres:9.4
  command: true
  volumes:
#Descomentar para publicar postgres en una carpeta del host (y sobrevivir a la eliminacion del container)
#   - ./docker-data/pgdata:/var/lib/postgresql/data
   - /var/lib/postgresql/data

#TODO: esto deberia existir para mantener los configs, logs y cache accesibles desde el host
#  - ./docker-data/instalacion:/var/local/portal/docker-data/instalacion


pg:
  image: postgres:9.4
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes_from:
   - data

memcached:
  image: memcached:latest

portal:
  image: siutoba/docker-portal:latest
  links:
   - memcached
   - pg
  ports:
   - "5000:80"
  volumes_from:
   - data
  volumes:
   - portal-core/:/var/local/portal/portal-core
  environment:
   SYMFONY_ENV: dev
   PORTAL_IDP_URL: http://localhost:4001/siu-arai-usuarios-idp


