## INSTALACION de Memcached y portal

data:
  image: postgres:9.4
  command: "true"
  volumes:
#Descomentar para publicar postgres en una carpeta del host (y sobrevivir a la eliminacion del container)
#   - ./docker-data/pgdata:/var/lib/postgresql/data
   - /var/lib/postgresql/data

#TODO: esto deberia existir para mantener los configs, logs y cache accesibles desde el host
#  - ./docker-data/portal-core:/var/local/docker-data/portal-core


pg:
  image: postgres:9.4
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes_from:
   - data

memcached:
  image: memcached:latest

portal-core:
  image: siutoba/docker-portal:latest
  container_name: portal-core
  links:
   - memcached
   - pg
  ports:
   - "5000:80"
  volumes_from:
   - data
  volumes:
   - ./portal-core/:/var/local/portal-core
  environment:
   DOCKER_WEB_SCRIPT           : /var/local/portal-core/bin/docker-instalar
   PORTAL_DB_HOST              : pg
   PORTAL_DB_NAME              : portal
   PORTAL_DB_PORT              : 5432
   PORTAL_DB_USERNAME          : postgres
   PORTAL_DB_PASSWORD          : postgres
   PORTAL_MEMCACHED_HOST       : memcached



